[package]
name = "rusty_status"
version = "0.1.0"
authors = ["Rui Pires <rui.pires@aptoide.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
